-- Oracle test SQL

-- Drop table if exists (Oracle syntax)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE test_table';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Create table
test_table
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    created_at DATE DEFAULT SYSDATE
);

-- Insert data
INSERT INTO test_table (name) VALUES ('Alice');
INSERT INTO test_table (name) VALUES ('Bob');
INSERT INTO test_table (name) VALUES ('Charlie');

-- Select data
SELECT * FROM test_table;

-- Update data
UPDATE test_table SET name = 'Alice Updated' WHERE name = 'Alice';

-- Delete data
DELETE FROM test_table WHERE name = 'Charlie';

-- Select after update/delete
SELECT * FROM test_table;

SELECT 1 FROM dual;
